### ISSUE TITLE
Do not put two assert one below another

### ISSUE THREAD

**Issue by dmuca** [agaped/academy#11]
https://github.com/agaped/academy/blob/9605ff328636c7af7c769b4e3310e87633f5244e/ListTest/src/test/java/ListInterfaceTest.java#L150

```
assert list.size() == 4 : "list not added at the begining";
assert list.get(0) == secondList.get(0) : "list not added ate the begining";
```

You should add these information to i.e. StringBuilder and print them both at the end, because if first assertion would fail, you don't know if the other also did.
Here is an example of how Tomek did it, you can check it:

https://github.com/tomeks86/list_api_test/blob/ce0a233c30a9f917f307f235e271341705a91e34/src/edu/tseidler/TestCase.java#L9

**Comment by agaped** [comment]
Good point, thanks for example.
